#!/usr/bin/env bash

launcher_script_dir="${launcher_script_dir:-"$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"}"
launcher_name="${launcher_name:-"focus"}"

function launch_focus {
    local history_file="$launcher_script_dir/$launcher_name-history"
    local IFS=$'\n'
    local windows=($(swaymsg -t get_tree| jq -r 'recurse(.nodes[]?) | recurse(.floating_nodes[]?) | select(.type=="con"), select(.type=="floating_con") | select((.app_id != null) or .name != null) | {id, app_id, name} | .id, .app_id, .name'))
    local str=""
    for ((i=0; i<"${#windows[@]}"; i=i+3)); do
        local id="${windows[i]}"
        local app_id="$(echo "${windows[i+1]}" | awk -F '.' '{print $NF}')"
        local name="${windows[i+2]}"

        local building_string=""
        if [[ $app_id != "null" ]]; 
        then
            building_string="$app_id "
        fi
        building_string="$building_string[$id]"
        if [[ $name != "null" ]];
        then
            building_string="$building_string: $name"
        fi
        str="$str$building_string\n" 
    done

    selection=$(printf $str | tofi --history=true --history-file=$history_file --fuzzy-match=true)
    [[ -z $selection ]] && return 1
    id=$(echo $selection | sed -r 's/^.*\[([^]]*).*$/\1/')
    if [[ -z $id ]]; then
        return 1
    fi
    swaymsg "[con_id=$id]" focus
    exit
}

launch_focus
