#!/usr/bin/env bash

# Interact with Bitwarden via `rbw`

# Load in the launch_array function
launcher_script_dir="${launcher_script_dir:-"$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"}"
launcher_name="${launcher_name:-"passwords"}"

function launcher {
    local history_file="$launcher_script_dir/$launcher_name-history"
    tofi --history=true --history-file=$history_file --prompt-text="Password: "
}

source "$LAUNCHERS/launch_array/launch_array"

function get_entry {
    local entries="$(rbw ls)"
    local entry_id="$(echo "$entries" | launcher)"
    echo "$entry_id"
}

function get_field {
    local entry_id="$1"
    if [ -n "$entry_id" ]; then
        echo "$(rbw get --raw "$entry_id" | jq '.data | keys[] ' | sed 's/"//g' | launcher)"
    fi
}

function launch_rbw_entry_field {
    local entry_id="$1"
    local field="$2"
    if [ -n "$entry_id" ]; then
        if [ -n "$field" ]; then
            (echo "$(rbw get "$entry_id" --field="$field")" | wl-copy --trim-newline --) && notify-send "$entry_id: $field now in clipboard"
        fi
    fi
}

function launch_rbw_entry {
    local entry_id="$1"
    local field="$(get_field "$entry_id")"
    launch_rbw_entry_field "$entry_id" "$field"
}

function launch_rbw_field {
    local field="$1"
    local entry_id="$(get_entry)"
    launch_rbw_entry_field "$entry_id" "$field"
}

function gen_pw {
    (echo "$(rbw generate 20)" | wl-copy --trim-newline --) && notify-send "generated password now in clipboard"
}

function launch_passwords {
    declare -A array=(
        ["Passwords"]="echo launch_rbw_field password"
        ["Usernames"]="echo launch_rbw_field username"
        ["Sync"]="rbw sync"
        ["Lock"]="rbw lock"
        ["Generate"]="echo gen_pw"
    )

    local entries="$(rbw ls)"
    while IFS=, read -r needle; do
        array["$needle"]="echo launch_rbw_entry '$needle'"
    done <<< "$entries"

    local result="$(launch_array $(typeset -p array))"
    if [ -n "$result" ]; then
        eval "$result"
    fi
}

launch_passwords
